# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

votingBanzhaf <- function(weights, quota) {
    .Call(`_CoopGame_votingBanzhaf`, weights, quota)
}

votingShapley <- function(weights, quota) {
    .Call(`_CoopGame_votingShapley`, weights, quota)
}

microarrayBanzhaf <- function(mtx) {
    .Call(`_CoopGame_microarrayBanzhaf`, mtx)
}

microarrayShapley <- function(mtx) {
    .Call(`_CoopGame_microarrayShapley`, mtx)
}

expressionsToFeaturesStd <- function(special, control) {
    .Call(`_CoopGame_expressionsToFeaturesStd`, special, control)
}

genesVotingBanzhaf <- function(special, control) {
    .Call(`_CoopGame_genesVotingBanzhaf`, special, control)
}

genesVotingShapley <- function(special, control) {
    .Call(`_CoopGame_genesVotingShapley`, special, control)
}

genesVotingPredict <- function(special, control, sample) {
    .Call(`_CoopGame_genesVotingPredict`, special, control, sample)
}

microarrayStrongestCoalition <- function(mtx, size) {
    .Call(`_CoopGame_microarrayStrongestCoalition`, mtx, size)
}

rcpp_hello_world <- function() {
    .Call(`_CoopGame_rcpp_hello_world`)
}

