# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

votingBanzhaf <- function(weights, quota) {
    .Call(`_CoopGame_votingBanzhaf`, weights, quota)
}

votingShapley <- function(weights, quota) {
    .Call(`_CoopGame_votingShapley`, weights, quota)
}

votingVal <- function(weights, quota, coal) {
    .Call(`_CoopGame_votingVal`, weights, quota, coal)
}

microarrayBanzhaf <- function(mtx) {
    .Call(`_CoopGame_microarrayBanzhaf`, mtx)
}

microarrayShapley <- function(mtx) {
    .Call(`_CoopGame_microarrayShapley`, mtx)
}

microarrayValue <- function(mtx, coal) {
    .Call(`_CoopGame_microarrayValue`, mtx, coal)
}

microarrayStrongestCoalition <- function(mtx, size) {
    .Call(`_CoopGame_microarrayStrongestCoalition`, mtx, size)
}

expressionsToFeaturesStd <- function(special, control) {
    .Call(`_CoopGame_expressionsToFeaturesStd`, special, control)
}

votingMicroarrayBanzhaf <- function(special, control) {
    .Call(`_CoopGame_votingMicroarrayBanzhaf`, special, control)
}

votingMicroarrayBanzhafTop <- function(special, control, topN) {
    .Call(`_CoopGame_votingMicroarrayBanzhafTop`, special, control, topN)
}

votingMicroarrayShapley <- function(special, control) {
    .Call(`_CoopGame_votingMicroarrayShapley`, special, control)
}

votingMicroarrayShapleyTop <- function(special, control, topN) {
    .Call(`_CoopGame_votingMicroarrayShapleyTop`, special, control, topN)
}

votingMicroarrayValue <- function(special, control, coal) {
    .Call(`_CoopGame_votingMicroarrayValue`, special, control, coal)
}

votingMicroarrayPredict <- function(special, control, sample) {
    .Call(`_CoopGame_votingMicroarrayPredict`, special, control, sample)
}

sumOfVotingBanzhaf <- function(weights, quotas) {
    .Call(`_CoopGame_sumOfVotingBanzhaf`, weights, quotas)
}

sumOfVotingShapley <- function(weights, quotas) {
    .Call(`_CoopGame_sumOfVotingShapley`, weights, quotas)
}

sumOfVotingValue <- function(weights, quotas, coal) {
    .Call(`_CoopGame_sumOfVotingValue`, weights, quotas, coal)
}

